package com.globant.splitcar.model.local

/**
 * RoadReferences
 *
 * This is the source of road references
 * It could be change to an API request in a future
 *
 */

val roadReference = listOf(
    RoadReference("1er Parque de Laureles"),
    RoadReference("Vizcaya"),
    RoadReference("2do Parque de Laureles"),
    RoadReference("Aldea Pablo VI"),
    RoadReference("Alejandro Echavarría"),
    RoadReference("Alejandría"),
    RoadReference("Alfonso López"),
    RoadReference("Altamira"),
    RoadReference("Altavista Sector Central"),
    RoadReference("Altavista"),
    RoadReference("Altos del Poblado"),
    RoadReference("Andalucía"),
    RoadReference("Antonio Nariño"),
    RoadReference("Aranjuez"),
    RoadReference("Asomadera No.1"),
    RoadReference("Asomadera No.2"),
    RoadReference("Asomadera No.3"),
    RoadReference("Astorga"),
    RoadReference("Atrio Iglesia Madre de Dios"),
    RoadReference("Atrio Iglesia San Bernardo"),
    RoadReference("Atrio Iglesia San Gregorio Magno"),
    RoadReference("Atrio Iglesia San Judas Tadeo"),
    RoadReference("Atrio Parroquia Santa Maria de Jesús"),
    RoadReference("Aures No.1"),
    RoadReference("Aures No.2"),
    RoadReference("Barrio Caicedo"),
    RoadReference("Barrio Colombia"),
    RoadReference("Barrio Colón"),
    RoadReference("Barrio Cristóbal"),
    RoadReference("Barrios de Jesús"),
    RoadReference("Barro Blanco"),
    RoadReference("Belalcázar"),
    RoadReference("Belencito"),
    RoadReference("Bello Horizonte"),
    RoadReference("Belén"),
    RoadReference("Berlín"),
    RoadReference("Bermejal-Los Álamos"),
    RoadReference("Betania"),
    RoadReference("Blanquizal"),
    RoadReference("Bomboná No.1"),
    RoadReference("Bomboná No.2"),
    RoadReference("Bosques de San Pablo"),
    RoadReference("Boston"),
    RoadReference("Boyacá"),
    RoadReference("Brasilia"),
    RoadReference("Buenos Aires"),
    RoadReference("Buga Patio Bonito"),
    RoadReference("Cabecera Urbana Corregimiento San Cristóbal"),
    RoadReference("Calasanz Parte Alta"),
    RoadReference("Calasanz"),
    RoadReference("Calle Nueva"),
    RoadReference("Campo Alegre"),
    RoadReference("Campo Amor"),
    RoadReference("Campo Valdés No.1"),
    RoadReference("Campo Valdés No.2"),
    RoadReference("Cancha de Futbol y Placa Polideportiva El Corazón"),
    RoadReference("Cancha de Fútbol Horizontes"),
    RoadReference("Cancha de Fútbol y Placa Polideportiva El Corazón"),
    RoadReference("Cancha Divina Providencia."),
    RoadReference("Cancha Fuente Clara"),
    RoadReference("Cancha Los Tablones"),
    RoadReference("Cancha Múltiple y Zona Verde"),
    RoadReference("Cancha San José del Manzanillo"),
    RoadReference("Cancha San Pablo"),
    RoadReference("Carlos E. Restrepo"),
    RoadReference("Carpinelo"),
    RoadReference("Casa de la Cultura Raíces de la Raza + Biblioteca"),
    RoadReference("Castilla"),
    RoadReference("Castropol"),
    RoadReference("Cataluña"),
    RoadReference("Cementerio Universal"),
    RoadReference("Centro Administrativo"),
    RoadReference("Centro Educativo Pedregal Alto"),
    RoadReference("Cerro La Asomadera"),
    RoadReference("Cerro Nutibara"),
    RoadReference("Chorro Clarín"),
    RoadReference("Ciudad Don Bosco"),
    RoadReference("Conectividad Quebrada Santa Elena - El Pinal"),
    RoadReference("Corazón de Jesús"),
    RoadReference("Corredor Ecológico Lineal La Iguaná"),
    RoadReference("Corredor Ecológico Lineal La Moreno"),
    RoadReference("Cristo Rey"),
    RoadReference("Cuarta Brigada"),
    RoadReference("Cucaracho"),
    RoadReference("Córdoba"),
    RoadReference("Diego Echavarría"),
    RoadReference("Doce de Octubre No.1"),
    RoadReference("Doce de Octubre No.2"),
    RoadReference("Ecoparque Cerro El Volador"),
    RoadReference("Eduardo Santos"),
    RoadReference("El Castillo"),
    RoadReference("El Chagualo"),
    RoadReference("El Compromiso"),
    RoadReference("El Corazón El Morro"),
    RoadReference("El Corazón"),
    RoadReference("El Danubio"),
    RoadReference("El Diamante No.2"),
    RoadReference("El Diamante"),
    RoadReference("El Nogal-Los Almendros"),
    RoadReference("El Pesebre"),
    RoadReference("El Pinal"),
    RoadReference("El Poblado"),
    RoadReference("El Pomar"),
    RoadReference("El Progreso"),
    RoadReference("El Raizal"),
    RoadReference("El Rincón"),
    RoadReference("El Salado"),
    RoadReference("El Salvador"),
    RoadReference("El Socorro"),
    RoadReference("El Tesoro"),
    RoadReference("El Triunfo"),
    RoadReference("El Velódromo"),
    RoadReference("Enciso"),
    RoadReference("EP Plan Parcial Pajarito"),
    RoadReference("Espacio Público Plan Parcial Pajarito"),
    RoadReference("Estación Metrocable Juan XXIII"),
    RoadReference("Estación Villa"),
    RoadReference("Estadio"),
    RoadReference("Facultad de Minas U. Nacional"),
    RoadReference("Ferrini"),
    RoadReference("Florencia"),
    RoadReference("Florida Nueva"),
    RoadReference("Francisco Antonio Zea"),
    RoadReference("Fuente Clara"),
    RoadReference("Fátima"),
    RoadReference("Gerona"),
    RoadReference("Girardot"),
    RoadReference("Granada"),
    RoadReference("Granizal"),
    RoadReference("Guayabal"),
    RoadReference("Guayaquil"),
    RoadReference("Héctor Abad Gómez"),
    RoadReference("I.E. Doce de Octubre"),
    RoadReference("I.E. Julio César García"),
    RoadReference("I.E. Las Independencias"),
    RoadReference("I.E. San José Obrero"),
    RoadReference("Iglesia Concilio Vaticano"),
    RoadReference("Iglesia San Felipe Neri"),
    RoadReference("Institución Educativa Doce de Octubre"),
    RoadReference("Institución Educativa Julio César García"),
    RoadReference("Institución Educativa Las Independencias"),
    RoadReference("Institución Educativa San José Obrero"),
    RoadReference("Jardín Botanico Joaquín Antonio Uribe"),
    RoadReference("Jardín Botánico Joaquín Antonio Uribe"),
    RoadReference("Jardín Botánico"),
    RoadReference("Jardín Comunitario Susanita Díaz"),
    RoadReference("Jardín Público Teatro Pablo Tobón Uribe"),
    RoadReference("Juan Pablo II"),
    RoadReference("Juan XXIII La Quiebra"),
    RoadReference("Kennedy"),
    RoadReference("Kilómetro Paisajístico"),
    RoadReference("La Aguacatala"),
    RoadReference("La Alpujarra"),
    RoadReference("La América"),
    RoadReference("La Avanzada"),
    RoadReference("La Candelaria"),
    RoadReference("La Castellana"),
    RoadReference("La Colina"),
    RoadReference("La Cruz"),
    RoadReference("La Esperanza No.2"),
    RoadReference("La Esperanza"),
    RoadReference("La Floresta"),
    RoadReference("La Florida"),
    RoadReference("La Francia"),
    RoadReference("La Frontera"),
    RoadReference("La Gloria"),
    RoadReference("La Hondonada"),
    RoadReference("La Isla"),
    RoadReference("La Ladera"),
    RoadReference("La Libertad"),
    RoadReference("La Loma de Los Bernal"),
    RoadReference("La Loma"),
    RoadReference("La Mansión"),
    RoadReference("La Milagrosa"),
    RoadReference("La Mota"),
    RoadReference("La Palma"),
    RoadReference("La Pilarica"),
    RoadReference("La Piñuela"),
    RoadReference("La Pradera"),
    RoadReference("La Rosa"),
    RoadReference("La Salle"),
    RoadReference("La Sierra"),
    RoadReference("Las Acacias"),
    RoadReference("Las Brisas"),
    RoadReference("Las Esmeraldas"),
    RoadReference("Las Estancias"),
    RoadReference("Las Granjas"),
    RoadReference("Las Independencias"),
    RoadReference("Las Lomas No.1"),
    RoadReference("Las Lomas No.2"),
    RoadReference("Las Mercedes"),
    RoadReference("Las Palmas"),
    RoadReference("Las Playas"),
    RoadReference("Las Violetas"),
    RoadReference("Laureles"),
    RoadReference("Llanaditas"),
    RoadReference("Lorena"),
    RoadReference("Loreto"),
    RoadReference("Los Alcázares"),
    RoadReference("Los Alpes"),
    RoadReference("Los Balsos No.1"),
    RoadReference("Los Balsos No.2"),
    RoadReference("Los Cerros El Vergel"),
    RoadReference("Los Colores"),
    RoadReference("Los Conquistadores"),
    RoadReference("Los Mangos"),
    RoadReference("Los Naranjos"),
    RoadReference("Los Pinos"),
    RoadReference("Los Ángeles"),
    RoadReference("López de  Mesa"),
    RoadReference("Manila"),
    RoadReference("Manrique Central No.1"),
    RoadReference("Manrique Central No.2"),
    RoadReference("Manrique Oriental"),
    RoadReference("Mazo"),
    RoadReference("Metropolitano"),
    RoadReference("Mirador Arcoiris"),
    RoadReference("Mirador de Calasanz"),
    RoadReference("Mirador de Palmitas"),
    RoadReference("Mirador del Doce"),
    RoadReference("Mirador Las Palmas"),
    RoadReference("Miraflores"),
    RoadReference("Miranda"),
    RoadReference("Miravalle"),
    RoadReference("Monteclaro"),
    RoadReference("Moravia"),
    RoadReference("Moscú No.1"),
    RoadReference("Moscú No.2"),
    RoadReference("Naranjal"),
    RoadReference("Nueva Villa de La Iguaná"),
    RoadReference("Nueva Villa del Aburrá"),
    RoadReference("Nuevos Conquistadores"),
    RoadReference("Ocho de Marzo"),
    RoadReference("Oleoducto"),
    RoadReference("Pablo VI"),
    RoadReference("Pajarito"),
    RoadReference("Palenque"),
    RoadReference("Palermo"),
    RoadReference("Palmitas Sector Central"),
    RoadReference("Parque Alcázares"),
    RoadReference("Parque Aliadas"),
    RoadReference("Parque Almería"),
    RoadReference("Parque Altamira"),
    RoadReference("Parque Ambiental Finca la Mesa"),
    RoadReference("Parque Ambiental Finca Montecarlo"),
    RoadReference("Parque Aranjuez"),
    RoadReference("Parque Bailarina Isabel Cristina Restrepo Cárdenas"),
    RoadReference("Parque Barrio Alfonso Lopez"),
    RoadReference("Parque Barrio Antioquia 1"),
    RoadReference("Parque Barrios de Jesús"),
    RoadReference("Parque Belén Los Alpes"),
    RoadReference("Parque Betania"),
    RoadReference("Parque Biblioteca La Ladera"),
    RoadReference("Parque Biblioteca San Javier"),
    RoadReference("Parque Biblioteca Tomás Carrasquilla"),
    RoadReference("Parque Bicentenario"),
    RoadReference("Parque Carlos E. Restrepo"),
    RoadReference("Parque Cedezo"),
    RoadReference("Parque Cementerio San Lorenzo"),
    RoadReference("Parque Centro Carcelario Metropolitano"),
    RoadReference("Parque Centro Logístico Servientrega"),
    RoadReference("Parque Centro Suramericana"),
    RoadReference("Parque Ciudad del Río"),
    RoadReference("Parque Colegio Presbítero Antonio José Bernal"),
    RoadReference("Parque Conjunto Residencial  Alcalá"),
    RoadReference("Parque Conquistadores"),
    RoadReference("Parque Contenedores Móviles"),
    RoadReference("Parque Cristo Rey"),
    RoadReference("Parque Cucaracho"),
    RoadReference("Parque Córdoba"),
    RoadReference("Parque de Belén"),
    RoadReference("Parque de Berrío"),
    RoadReference("Parque de Bolívar"),
    RoadReference("Parque de Boston"),
    RoadReference("Parque de La Curva"),
    RoadReference("Parque de La Escalera"),
    RoadReference("Parque de La Piñuela"),
    RoadReference("Parque de la República"),
    RoadReference("Parque de las Terminalias"),
    RoadReference("Parque de los Deseos"),
    RoadReference("Parque de los Pies Descalzos"),
    RoadReference("Parque de Los Tanques"),
    RoadReference("Parque de Manrique Central N°1"),
    RoadReference("Parque de San Cristóbal"),
    RoadReference("Parque de Skate Santo Domingo"),
    RoadReference("Parque de Villa Hermosa"),
    RoadReference("Parque del Cerro Pan de Azúcar"),
    RoadReference("Parque del Periodista"),
    RoadReference("Parque del Viento"),
    RoadReference("Parque Deportivo Antonio Nariño"),
    RoadReference("Parque Deportivo Belén La Palma"),
    RoadReference("Parque Deportivo El Rincón"),
    RoadReference("Parque Deportivo El Salado"),
    RoadReference("Parque Deportivo El Socorro"),
    RoadReference("Parque Deportivo La Maracaná"),
    RoadReference("Parque Deportivo Santa Lucía"),
    RoadReference("Parque Deportivo Sede Social La Pradera Parte Baja"),
    RoadReference("Parque Diego Echavarría"),
    RoadReference("Parque Divina Eucaristía"),
    RoadReference("Parque Doce de Octubre 1 Unidad Hospitalaria"),
    RoadReference("Parque Doce de Octubre 2"),
    RoadReference("Parque Doce de Octubre La Torre 1"),
    RoadReference("Parque Ecológico Cerro Nutibara"),
    RoadReference("Parque Ecológico La Perla"),
    RoadReference("Parque Ecológico Los Vikingos"),
    RoadReference("Parque Ecológico Quebrada La Mansión"),
    RoadReference("Parque Eduardo Santos"),
    RoadReference("Parque Efe Gómez"),
    RoadReference("Parque El Ajedrez"),
    RoadReference("Parque El Calvario"),
    RoadReference("Parque El Corazón"),
    RoadReference("Parque El Limonar III"),
    RoadReference("Parque El Molino"),
    RoadReference("Parque El Progreso"),
    RoadReference("Parque El Rodeo"),
    RoadReference("Parque El Silletero Núcleo Central"),
    RoadReference("Parque El Vergel"),
    RoadReference("Parque Florida Nueva"),
    RoadReference("Parque Francisco Antonio Zea"),
    RoadReference("Parque Gratamira"),
    RoadReference("Parque I.E. Luis López de Mesa"),
    RoadReference("Parque Iglesia del Perpetuo Socorro"),
    RoadReference("Parque Iglesia Nuestra Señora de Fátima"),
    RoadReference("Parque Iglesia San Agustín"),
    RoadReference("Parque Iglesia Santa Mónica"),
    RoadReference("Parque Iglesia Santa Teresita del Niño Jesús"),
    RoadReference("Parque Infantil Barrios de Jesús"),
    RoadReference("Parque Infantil Bomberos"),
    RoadReference("Parque Infantil Centro Comercial Oviedo"),
    RoadReference("Parque Infantil El Compromiso"),
    RoadReference("Parque Infantil El Mirador"),
    RoadReference("Parque Infantil El Rosario"),
    RoadReference("Parque Infantil Fátima"),
    RoadReference("Parque Infantil La Isla"),
    RoadReference("Parque Infantil Las Brisas"),
    RoadReference("Parque Infantil Los Mangos"),
    RoadReference("Parque Infantil Pablo VI"),
    RoadReference("Parque Infantil Popular"),
    RoadReference("Parque Infantil Santa Lucía"),
    RoadReference("Parque Infantil Urb. Quintanar de Toledo II"),
    RoadReference("Parque Infantil"),
    RoadReference("Parque Institución Educativa Luis López de Mesa"),
    RoadReference("Parque Israel"),
    RoadReference("Parque J.F. Kennedy - Estación Floresta"),
    RoadReference("Parque Jorge Eliécer Gaitán"),
    RoadReference("Parque Juan Pablo II"),
    RoadReference("Parque Juanes De La Paz"),
    RoadReference("Parque La Almería"),
    RoadReference("Parque La América"),
    RoadReference("Parque La Castellana"),
    RoadReference("Parque La Chinca"),
    RoadReference("Parque La Colina"),
    RoadReference("Parque La Colinita 1"),
    RoadReference("Parque La Floresta"),
    RoadReference("Parque La Gloria"),
    RoadReference("Parque La Madre"),
    RoadReference("Parque La Matea"),
    RoadReference("Parque La Mattina"),
    RoadReference("Parque La Milagrosa"),
    RoadReference("Parque La Mota"),
    RoadReference("Parque La Nubia"),
    RoadReference("Parque La Pradera"),
    RoadReference("Parque Las Américas"),
    RoadReference("Parque Las Brisas"),
    RoadReference("Parque Las Independencias"),
    RoadReference("Parque Las Mercedes"),
    RoadReference("Parque Las Mirlas"),
    RoadReference("Parque Las Playas"),
    RoadReference("Parque Lineal Bosques de la Frontera"),
    RoadReference("Parque Lineal de Los Sentidos"),
    RoadReference("Parque Lineal Quebrada El Salado"),
    RoadReference("Parque Lineal Quebrada La Batea"),
    RoadReference("Parque Lineal Quebrada La Bermejala"),
    RoadReference("Parque Lineal Quebrada La Herrera"),
    RoadReference("Parque Lineal Quebrada La India"),
    RoadReference("Parque Lineal Quebrada La Malpaso"),
    RoadReference("Parque Lineal Quebrada La Presidenta"),
    RoadReference("Parque Lineal Quebrada La Quintana Fase 1"),
    RoadReference("Parque Lineal Quebrada La Quintana"),
    RoadReference("Parque Lineal Quebrada La Tinaja"),
    RoadReference("Parque Lleras"),
    RoadReference("Parque Loma del Garabato"),
    RoadReference("Parque Lorena"),
    RoadReference("Parque Los Almendros"),
    RoadReference("Parque Los Cerros I"),
    RoadReference("Parque Los Colores"),
    RoadReference("Parque Los Conquistadores"),
    RoadReference("Parque Los Jubilados"),
    RoadReference("Parque Los Mangos"),
    RoadReference("Parque Los Naranjos"),
    RoadReference("Parque Lourdes"),
    RoadReference("Parque Malibú"),
    RoadReference("Parque Manila"),
    RoadReference("Parque Manzanares"),
    RoadReference("Parque Maria Auxiliadora"),
    RoadReference("Parque Mayorca"),
    RoadReference("Parque Metrocable Occidente"),
    RoadReference("Parque Mirador Cancha"),
    RoadReference("Parque Miravalle 1"),
    RoadReference("Parque Miravalle 2"),
    RoadReference("Parque Monumento a La Virgen"),
    RoadReference("Parque Monumento Simesa"),
    RoadReference("Parque Natural Metropolitano Cerro El Volador"),
    RoadReference("Parque Norte"),
    RoadReference("Parque Obrero"),
    RoadReference("Parque Paraguay"),
    RoadReference("Parque Pilarica"),
    RoadReference("Parque Pinocho"),
    RoadReference("Parque Plaza Colón"),
    RoadReference("Parque Plaza de la Libertad"),
    RoadReference("Parque Principal El Poblado"),
    RoadReference("Parque Principal San Antonio de Prado"),
    RoadReference("Parque Quimbaya"),
    RoadReference("Parque Rafael J. Mejía"),
    RoadReference("Parque Recreativo Bosques de San Pablo"),
    RoadReference("Parque Recreativo Cataluña No.1"),
    RoadReference("Parque Recreativo Cataluña No.2"),
    RoadReference("Parque Recreativo El Salvador"),
    RoadReference("Parque Recreativo Estación Caribe Metro"),
    RoadReference("Parque Recreativo infantil"),
    RoadReference("Parque Recreativo La Ocho"),
    RoadReference("Parque Recreativo Loreto"),
    RoadReference("Parque Recreativo Pablo Vi"),
    RoadReference("Parque Recreativo Pablo VI"),
    RoadReference("Parque Recreativo Policarpa Salavarrieta"),
    RoadReference("Parque Recreativo Santa Fe"),
    RoadReference("Parque Recreativo Santa Inés"),
    RoadReference("Parque Recreativo Trinidad"),
    RoadReference("Parque Recreativo Versalles"),
    RoadReference("Parque Recreativo"),
    RoadReference("Parque Reversadero I - Las Independencias"),
    RoadReference("Parque Robledo"),
    RoadReference("Parque San Antonio"),
    RoadReference("Parque San Carlos"),
    RoadReference("Parque San Joaquín"),
    RoadReference("Parque San Pablo"),
    RoadReference("Parque Santa Lucía"),
    RoadReference("Parque Santa María de Los Ángeles No.1"),
    RoadReference("Parque Santa María de Los Ángeles No.2"),
    RoadReference("Parque Santander"),
    RoadReference("Parque Sector Central"),
    RoadReference("Parque Sede Comunal Juan XXIII"),
    RoadReference("Parque Simona Duque"),
    RoadReference("Parque Suramericana"),
    RoadReference("Parque Terrazas"),
    RoadReference("Parque Tomas Cipriano de Mosquera"),
    RoadReference("Parque Travesías Sector La Cumbre"),
    RoadReference("Parque Unidad Residencial Manila"),
    RoadReference("Parque Urb. Aguas del Bosque"),
    RoadReference("Parque Urb. Aldea Guayabal"),
    RoadReference("Parque Urb. Alejandro Echavarría"),
    RoadReference("Parque Urb. Ciudadela Prado II"),
    RoadReference("Parque Urb. Colinas del Viento"),
    RoadReference("Parque Urb. Compartir"),
    RoadReference("Parque Urb. El Limonar II"),
    RoadReference("Parque Urb. El Pinar"),
    RoadReference("Parque Urb. La Alborada"),
    RoadReference("Parque Urb. La Carmelita"),
    RoadReference("Parque Urb. La Milagrosa"),
    RoadReference("Parque Urb. Leonardo Davinci"),
    RoadReference("Parque Urb. Matisse y Miró"),
    RoadReference("Parque Urb. Parques de Villa Carlota"),
    RoadReference("Parque Urb. Patio de las Fuentes"),
    RoadReference("Parque Urb. Pinar del Río"),
    RoadReference("Parque Urb. Prados del Este"),
    RoadReference("Parque Urb. Puente Jardín"),
    RoadReference("Parque Urb. Quintas del Plantío"),
    RoadReference("Parque Urb. Rincón del Aguacatal"),
    RoadReference("Parque Urb. San Fernando Plaza"),
    RoadReference("Parque Urb. Sananghelis"),
    RoadReference("Parque Urb. Santa Ana de los Balsos"),
    RoadReference("Parque Urb. Solaris"),
    RoadReference("Parque Urb. Tesoro La Y"),
    RoadReference("Parque Urb. Torre Laguna"),
    RoadReference("Parque Urb. Torres de la Visitación"),
    RoadReference("Parque Urb. Villa Loma"),
    RoadReference("Parque Urb. Ávila"),
    RoadReference("Parque Urbanización Aguas del Bosque"),
    RoadReference("Parque Urbanización Aldea Guayabal"),
    RoadReference("Parque Urbanización Alejandro Echavarría"),
    RoadReference("Parque Urbanización Ciudadela Prado II"),
    RoadReference("Parque Urbanización Colinas del Viento"),
    RoadReference("Parque Urbanización Compartir"),
    RoadReference("Parque Urbanización El Limonar II"),
    RoadReference("Parque Urbanización El Pinar"),
    RoadReference("Parque Urbanización La Alborada"),
    RoadReference("Parque Urbanización La Carmelita"),
    RoadReference("Parque Urbanización La Milagrosa"),
    RoadReference("Parque Urbanización Leonardo Davinci"),
    RoadReference("Parque Urbanización Matisse y Miró"),
    RoadReference("Parque Urbanización Parques de Villa Carlota"),
    RoadReference("Parque Urbanización Patio de las Fuentes"),
    RoadReference("Parque Urbanización Pinar del Río"),
    RoadReference("Parque Urbanización Prados del Este"),
    RoadReference("Parque Urbanización Puente Jardín"),
    RoadReference("Parque Urbanización Quintas del Plantío"),
    RoadReference("Parque Urbanización Rincón del Aguacatal"),
    RoadReference("Parque Urbanización San Fernando Plaza"),
    RoadReference("Parque Urbanización Sananghelis"),
    RoadReference("Parque Urbanización Santa Ana de los Balsos"),
    RoadReference("Parque Urbanización Solaris"),
    RoadReference("Parque Urbanización Tesoro La Y"),
    RoadReference("Parque Urbanización Torre Laguna"),
    RoadReference("Parque Urbanización Torres de la Visitación"),
    RoadReference("Parque Urbanización Villa Loma"),
    RoadReference("Parque Urbanización Ávila"),
    RoadReference("Parque Vegas de Alcalá"),
    RoadReference("Parque Villa del Socorro"),
    RoadReference("Parque y Monumento El Salvador"),
    RoadReference("Parque"),
    RoadReference("Parroquia Corpus Cristi"),
    RoadReference("Parroquia La Divina Gracia"),
    RoadReference("Parroquia San Fernando"),
    RoadReference("Parroquia Santa María del Carmen"),
    RoadReference("Pasaje Uribe Uribe"),
    RoadReference("Patio Bonito"),
    RoadReference("Pedregal Alto"),
    RoadReference("Pedregal"),
    RoadReference("Perpetuo Socorro"),
    RoadReference("Picachito"),
    RoadReference("Picacho"),
    RoadReference("Piedras Blancas - Matasano"),
    RoadReference("Placa Polideportiva Betania"),
    RoadReference("Placa Polideportiva Córdoba"),
    RoadReference("Placa Polideportiva La Capilla"),
    RoadReference("Placa Polideportiva"),
    RoadReference("Playón de Los Comuneros"),
    RoadReference("Plaza Botero"),
    RoadReference("Plaza Cívica San Antonio"),
    RoadReference("Plaza de Eventos Villa Suramericana"),
    RoadReference("Plaza de Ferias"),
    RoadReference("Plaza de la Luz"),
    RoadReference("Plaza Gardel"),
    RoadReference("Plaza Mayor"),
    RoadReference("Plaza Mazo"),
    RoadReference("Plaza Talleres Robledo"),
    RoadReference("Plazoleta Bancolombia"),
    RoadReference("Plazoleta Barrio Colón"),
    RoadReference("Plazoleta Carlos Gardel"),
    RoadReference("Plazoleta Central Palmitas"),
    RoadReference("Plazoleta Centro Educativo Bucarelly"),
    RoadReference("Plazoleta Estación Hospital"),
    RoadReference("Plazoleta Estación Poblado"),
    RoadReference("Plazoleta Estación Prado 1"),
    RoadReference("Plazoleta Estación Prado 2"),
    RoadReference("Plazoleta Gorda de Botero"),
    RoadReference("Plazoleta Granizal"),
    RoadReference("Plazoleta Hospital General"),
    RoadReference("Plazoleta Iglesia de San José"),
    RoadReference("Plazoleta La Alpujarra"),
    RoadReference("Plazoleta La Veracruz"),
    RoadReference("Plazoleta Puente La Aguacatala"),
    RoadReference("Plazoleta Punto Clave"),
    RoadReference("Plazoleta San Antonio"),
    RoadReference("Plazoleta Suramericana"),
    RoadReference("Plazoleta Terminal de Transporte"),
    RoadReference("Plazoleta Trece de Noviembre"),
    RoadReference("Plazoleta U.D. Atanasio Girardot"),
    RoadReference("Plazoleta Unidad Deportiva Atanasio Girardot"),
    RoadReference("Plazoleta Urb. Santillana"),
    RoadReference("Plazoleta Urb. Sao Paulo"),
    RoadReference("Plazoleta Urb. Villa de Aburrá"),
    RoadReference("Plazoleta Urb. Villa Suramericana"),
    RoadReference("Plazoleta Urbanización Santillana"),
    RoadReference("Plazoleta Urbanización Sao Paulo"),
    RoadReference("Plazoleta Urbanización Villa de Aburrá"),
    RoadReference("Plazoleta Urbanización Villa Suramericana"),
    RoadReference("Plazoleta Área de Expansión San Antonio"),
    RoadReference("Plazuela Francisco Antonio Zea"),
    RoadReference("Plazuela Manuel Jose Caycedo"),
    RoadReference("Plazuela Manuel José Caycedo"),
    RoadReference("Plazuela Mon y Velarde"),
    RoadReference("Plazuela Nutibara"),
    RoadReference("Plazuela Rojas Pinilla"),
    RoadReference("Plazuela San Ignacio"),
    RoadReference("Polideportivo de Aliadas"),
    RoadReference("Polideportivo"),
    RoadReference("Popular"),
    RoadReference("Potrerito"),
    RoadReference("Prado"),
    RoadReference("Progreso No.2"),
    RoadReference("Retiro de Quebrada Bella Vista"),
    RoadReference("Retiro de Quebrada La Pelahueso"),
    RoadReference("Retiro de Quebrada"),
    RoadReference("Robledo"),
    RoadReference("Rosales"),
    RoadReference("S.E. Alfredo Cock Arango"),
    RoadReference("S.E. República de Cuba"),
    RoadReference("San Antonio de Prado"),
    RoadReference("San Benito"),
    RoadReference("San Bernardo"),
    RoadReference("San Diego"),
    RoadReference("San Germán"),
    RoadReference("San Isidro"),
    RoadReference("San Javier No.1"),
    RoadReference("San Javier No.2"),
    RoadReference("San Joaquín"),
    RoadReference("San José del Manzanillo"),
    RoadReference("San José La Cima No.1"),
    RoadReference("San Lucas"),
    RoadReference("San Martín de Porres"),
    RoadReference("San Miguel"),
    RoadReference("San Pablo"),
    RoadReference("San Pedro"),
    RoadReference("Santa Cruz"),
    RoadReference("Santa Elena Sector Central"),
    RoadReference("Santa Fé"),
    RoadReference("Santa Inés"),
    RoadReference("Santa Lucía"),
    RoadReference("Santa Margarita"),
    RoadReference("Santa María de Los Ángeles"),
    RoadReference("Santa Mónica"),
    RoadReference("Santa Rosa de Lima"),
    RoadReference("Santa Teresita"),
    RoadReference("Santander"),
    RoadReference("Santo Domingo Savio No.1"),
    RoadReference("Sección Escuela Alfredo Cock Arango"),
    RoadReference("Sección Escuela República de Cuba"),
    RoadReference("Sede Social Santa Rosa de Lima"),
    RoadReference("Sevilla"),
    RoadReference("Simón Bolívar"),
    RoadReference("Sin Nombre"),
    RoadReference("Sucre"),
    RoadReference("Suramericana"),
    RoadReference("Tejelo"),
    RoadReference("Tenche"),
    RoadReference("Terminal de Transporte"),
    RoadReference("Toscana"),
    RoadReference("Travesías"),
    RoadReference("Trece de Noviembre"),
    RoadReference("Tricentenario"),
    RoadReference("Trinidad"),
    RoadReference("U.D. Andrés Escobar"),
    RoadReference("U.D. Atanasio Girardot"),
    RoadReference("U.D. Barrio Cristóbal"),
    RoadReference("U.D. de Belén"),
    RoadReference("U.D. de Castilla"),
    RoadReference("U.D. Doce de Octubre"),
    RoadReference("U.D. La Floresta"),
    RoadReference("U.D. San Cristóbal"),
    RoadReference("Unidad Deportiva Andrés Escobar"),
    RoadReference("Unidad Deportiva Barrio Cristóbal"),
    RoadReference("Unidad Deportiva de Belén"),
    RoadReference("Unidad Deportiva de Castilla"),
    RoadReference("Unidad Deportiva Doce de Octubre"),
    RoadReference("Unidad Deportiva La Floresta"),
    RoadReference("Unidad Deportiva San Cristóbal"),
    RoadReference("Universidad Nacional"),
    RoadReference("Veinte de Julio"),
    RoadReference("Versalles No.1"),
    RoadReference("Villa Carlota"),
    RoadReference("Villa del Socorro"),
    RoadReference("Villa Flora"),
    RoadReference("Villa Guadalupe"),
    RoadReference("Villa Hermosa"),
    RoadReference("Villa Lilliam"),
    RoadReference("Villa Niza"),
    RoadReference("Villa Nueva"),
    RoadReference("Villa Turbay"),
    RoadReference("Villatina"),
    RoadReference("Volcana Guayabal"),
    RoadReference("Z.V. - Parque Infantil Pablo VI"),
    RoadReference("Z.V. La Cristóbal"),
    RoadReference("Z.V. Pajarito"),
    RoadReference("Z.V. Sector Central"),
    RoadReference("Z.V. Suramericana"),
    RoadReference("Z.V. Urb. Altavista Los Cerezos"),
    RoadReference("Z.V. Urb. Carlos E. Restrepo"),
    RoadReference("Z.V. Urb. La Praga"),
    RoadReference("Z.V. Urb. Mano de Dios"),
    RoadReference("Z.V. Urb. Nueva Villa de Aburrá"),
    RoadReference("Z.V. Urb. Piamonte"),
    RoadReference("Z.V. Urb. San Gabriel"),
    RoadReference("Z.V. Villa de Santa Catalina"),
    RoadReference("Zona Comunal No 3 Caunces"),
    RoadReference("Zona Comunal Urbanización Pradera Verde"),
    RoadReference("Zona Verde La Cristóbal"),
    RoadReference("Zona Verde Pajarito"),
    RoadReference("Zona Verde Parque Infantil"),
    RoadReference("Zona Verde Sector Central"),
    RoadReference("Zona Verde Suramericana"),
    RoadReference("Zona Verde Urbanización Altavista Los Cerezos"),
    RoadReference("Zona Verde Urbanización Carlos E. Restrepo"),
    RoadReference("Zona Verde Urbanización La Praga"),
    RoadReference("Zona Verde Urbanización Mano de Dios"),
    RoadReference("Zona Verde Urbanización Nueva Villa de Aburrá"),
    RoadReference("Zona Verde Urbanización Piamonte"),
    RoadReference("Zona Verde Urbanización San Gabriel"),
    RoadReference("Zona Verde Villa de Santa Catalina"),
    RoadReference("Zona Verde y Parque Infantil Pablo VI"),
    RoadReference("Zona Verde"),
    RoadReference("Área de Expansión Altavista"),
    RoadReference("Área de Expansión Belén Rincón"),
    RoadReference("Área de Expansión Pajarito"),
    RoadReference("Área de Expansión San Antonio de Prado"),
    RoadReference("Área de Recreación Parque Ecológico Cerro Nutibara"),
    RoadReference("Área de Recreación Urbana Cerro La Asomadera")
)

fun getDefaultRoadReferenceList(): List<RoadReference> {
    return roadReference
}